DROP DATABASE IF EXISTS CRUD_ADT;
CREATE DATABASE IF NOT EXISTS CRUD_ADT;
USE CRUD_ADT;

CREATE TABLE PROFILE_(
  PROFILE_CODE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  EMAIL VARCHAR (40) UNIQUE,
  USER_NAME VARCHAR (30) UNIQUE,
  PSWD TEXT,
  TELEPHONE BIGINT,
  NAME_ VARCHAR (30),
  SURNAME VARCHAR (30)
);

CREATE TABLE USER_(
  PROFILE_CODE INT NOT NULL PRIMARY KEY,
  GENDER VARCHAR (10),
  CARD_NO VARCHAR (50),
  FOREIGN KEY (PROFILE_CODE) REFERENCES PROFILE_(PROFILE_CODE) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE ADMIN_(
  PROFILE_CODE INT NOT NULL PRIMARY KEY,
  CURRENT_ACCOUNT VARCHAR (50),
  FOREIGN KEY (PROFILE_CODE) REFERENCES PROFILE_(PROFILE_CODE) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE SHOE (
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  PRICE DOUBLE NOT NULL,
  MODEL VARCHAR(30) NOT NULL,
  SIZE DOUBLE NOT NULL,
  EXCLUSIVE ENUM ('TRUE', 'FALSE') DEFAULT 'FALSE',
  MANUFACTER_DATE DATE,
  COLOR VARCHAR(20) NOT NULL,
  ORIGIN VARCHAR(20) NOT NULL,
  BRAND VARCHAR(20) NOT NULL,
  RESERVED ENUM('TRUE', 'FALSE') DEFAULT 'FALSE',
  STOCK INT,
  IMAGE_FILE VARCHAR(120) NULL
);

CREATE TABLE ORDER_ (
  ORDER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  PROFILE_CODE INT NOT NULL,
  SHOE_ID INT NOT NULL,
  DATE_ DATE NOT NULL,
  QUANTITY INT NOT NULL,
  FOREIGN KEY (PROFILE_CODE) REFERENCES USER_(PROFILE_CODE) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (SHOE_ID) REFERENCES SHOE(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);

INSERT INTO PROFILE_ (PROFILE_CODE, EMAIL, USER_NAME, PSWD, TELEPHONE, NAME_, SURNAME) VALUES
(1, 'juan.perez@email.com', 'juanP', '$2y$10$qhS3KKOox0S.aNVbYWp7VunfmP/lCHYqoxdCM10KMjScgPO5JiMFy', 611223344, 'Juan', 'Pérez'),
(2, 'maria.garcia@email.com', 'mariag', '$2y$10$qhS3KKOox0S.aNVbYWp7VunfmP/lCHYqoxdCM10KMjScgPO5JiMFy', 622334455, 'María', 'García'),
(3, 'carlos.lopez@email.com', 'carlosl', '$2y$10$qhS3KKOox0S.aNVbYWp7VunfmP/lCHYqoxdCM10KMjScgPO5JiMFy', 633445566, 'Carlos', 'López'),
(4, 'ana.martinez@email.com', 'anam', '$2y$10$qhS3KKOox0S.aNVbYWp7VunfmP/lCHYqoxdCM10KMjScgPO5JiMFy', 644556677, 'Ana', 'Martínez'),
(5, 'pedro.rodriguez@email.com', 'pedror', '$2y$10$qhS3KKOox0S.aNVbYWp7VunfmP/lCHYqoxdCM10KMjScgPO5JiMFy', 655667788, 'Pedro', 'Rodríguez');

INSERT INTO USER_ (PROFILE_CODE, GENDER, CARD_NO) VALUES
(1, 'Man', 'AA1234567890123456'),
(2, 'Female', 'AA2345678901234567'),
(3, 'Man', 'AA3456789012345678');

INSERT INTO ADMIN_ (PROFILE_CODE, CURRENT_ACCOUNT) VALUES
(4, 'ES123456789012345678'),
(5, 'ES987654321098765432');


INSERT INTO SHOE 
(PRICE, MODEL, SIZE, EXCLUSIVE, MANUFACTER_DATE, COLOR, ORIGIN, BRAND, RESERVED, STOCK, IMAGE_FILE)
VALUES
(79.99, 'Air Max', 42, 'FALSE', '2024-01-10', 'Negro', 'España', 'Nike', 'FALSE', 50, 'nike_airmax90_negras.jpg'),
(79.99, 'Air Max', 45, 'FALSE', '2024-01-10', 'Negro', 'España', 'Nike', 'FALSE', 50, 'nike_airmax90_negras.jpg'),
(120.50, 'Samba', 40, 'TRUE', '2023-11-05', 'Negro', 'Italia', 'Adidas', 'FALSE', 30, 'adidas_samba_negras.jpg'),
(95.00, 'Caven', 41, 'FALSE', '2024-02-20', 'Azul', 'Portugal', 'Puma', 'TRUE', 10, 'puma_caven_azul.jpg');

INSERT INTO ORDER_ 
(PROFILE_CODE, SHOE_ID, DATE_, QUANTITY)
VALUES
(1, 1, '2024-03-01', 1),  
(2, 2, '2024-03-02', 2),
(3, 3, '2024-03-05', 1), 
(1, 3, '2024-03-10', 1); 

DELIMITER //
CREATE PROCEDURE RegistrarUsuario(IN p_username VARCHAR(30), IN p_pswd TEXT)
BEGIN
  DECLARE nuevo_profile_code INT;
  
  INSERT INTO PROFILE_ (EMAIL, USER_NAME, PSWD, TELEPHONE, NAME_, SURNAME)
  VALUES (NULL, p_username, p_pswd, NULL, NULL, NULL);

  SET nuevo_profile_code = LAST_INSERT_ID();

  INSERT INTO USER_ (PROFILE_CODE, GENDER, CARD_NO)
  VALUES (nuevo_profile_code, NULL, NULL);
  
  SELECT * 
  FROM PROFILE_ P, USER_ U 
  WHERE P.PROFILE_CODE = U.PROFILE_CODE 
    AND P.PROFILE_CODE = nuevo_profile_code;
END //
DELIMITER ;